bugfix - 修复管理员权限相关bug
TencentBlueKing/bk-training-open pull request #200
Opened 2021-12-17 16:22 UTC by XaviZhang-jy

1.非管理员看不到管理组页面
2.非管理员禁用添加成员按钮
3.非管理员不显示操作栏
4.管理员移除成员时先出弹框
5.选中组名后，刷新页面，会恢复为已选中的小组

2021-12-17 16:45 UTC, OrenZhang commented on frontend/src/views/myGroup/index.vue
> +                const storage = window.sessionStorage
应该不用加window吧

2021-12-17 16:46 UTC, OrenZhang commented on home_application/utils/tools.py
> +def check_user_is_admin(request, key):
key的辨识度不够高

2021-12-17 16:47 UTC, OrenZhang commented on home_application/utils/tools.py
> +    if key:
这里细看似乎有逻辑问题，只要有一个组不是管理员，直接返回False了

2021-12-17 16:47 UTC, OrenZhang requested changes
*

2021-12-17 17:33 UTC, XaviZhang-jy commented on home_application/utils/tools.py
> +    if key:
逻辑上只要在一个组不是管理员，就需要写日报，是这个作用

2021-12-18 04:35 UTC, OrenZhang approved these changes

2021-12-18 04:35 UTC, merged