sprintfix:邮件格式修改
TencentBlueKing/bk-training-open pull request #221
Opened 2021-12-24 06:32 UTC by xingcheno

2021-12-24 10:33 UTC, OrenZhang commented on home_application/admin_views.py
> +    evaluate_name = evaluate_name.username + "(" + evaluate_name.name + ")"
命名规范一下 `evaluate_name.username` 看着不对劲

2021-12-24 10:34 UTC, OrenZhang commented on home_application/admin_views.py
> +        all_username = all_username[0] + "(" + all_username[1] + ")"
命名规范
`all_username = all_username[0] + "(" + all_username[1] + ")"`

2021-12-24 10:35 UTC, OrenZhang commented on home_application/admin_views.py
> +        all_username = ",".join(all_username_name_list)
命名规范 `all_username_name_list`

2021-12-24 10:35 UTC, OrenZhang commented on home_application/admin_views.py
> +                "evaluate_name": evaluate_name.username + "(" + evaluate_name.name + ")",
命名规范  `evaluate_name.username`

2021-12-24 10:35 UTC, OrenZhang commented on home_application/templates/email_templates/all_excellent.html
> +                                  href="{{group_link}}">点击查看</a>
`<a>` 标签换行

2021-12-24 10:36 UTC, OrenZhang commented on home_application/templates/email_templates/all_excellent.html
> +        <table style="width: 800px; margin: 36px auto; border-collapse: collapse;">
`width: 800px` -> `max-width: 800px`

2021-12-24 10:36 UTC, OrenZhang commented on home_application/templates/email_templates/excellent.html
> +<!--用户日志-->
不用的注释就删掉哈

2021-12-24 10:37 UTC, OrenZhang commented on home_application/templates/email_templates/group_daily.html
> +                    <td  colspan="4" style="width: 30%; font-size: 16px">
width: 30%;

2021-12-24 10:38 UTC, OrenZhang commented on home_application/utils/mail_operation.py
> +            "people_in_vacation_count": len(group_info["off_day_name_list"]),  # TODO 请假人数
`# TODO` ？

2021-12-24 10:39 UTC, OrenZhang requested changes
*

2021-12-25 11:03 UTC, xingcheno reviewed
sprintfix:修改评价发送给被评价人，一键分享日报和每天十点日报推送的邮件样式

2021-12-25 11:03 UTC, OrenZhang approved these changes

2021-12-25 11:04 UTC, merged